# Generated by Django 2.0.6 on 2018-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180813_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatars/if_female1_403023.svg', upload_to='avatars'),
        ),
    ]
